
title: The Weather Report
author: Andrew Tenno
description: >- # this means to ignore newlines until "baseurl:"
  Hiking reports, rambles, and thoughts about everything but the weather.
show_excerpts: false # set to true to show excerpts on the homepage

header_pages:
  - running.markdown
  - hiking.markdown
  - about.markdown

github_username:  andrewtenno
linkedin_username:  andrew-tenno
twitter_username: nintenno
instagram_username: andrewtenno

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
